In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [14]:

df = pd.read_csv(r"C:\Users\alpha\Downloads\Sample-Superstore.csv")
df.head()

,csvbase_row_id,﻿Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [15]:
df.tail()

,csvbase_row_id,﻿Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   csvbase_row_id  9994 non-null   int64
 1   ﻿Row ID         9994 non-null   int64
 2   Order ID        9994 non-null   object
 3   Order Date      9994 non-null   object
 4   Ship Date       9994 non-null   object
 5   Ship Mode       9994 non-null   object
 6   Customer ID     9994 non-null   object
 7   Customer Name   9994 non-null   object
 8   Segment         9994 non-null   object
 9   Country         9994 non-null   object
 10  City            9994 non-null   object
 11  State           9994 non-null   object
 12  Postal Code     9994 non-null   int64
 13  Region          9994 non-null   object
 14  Product ID      9994 non-null   object
 15  Category        9994 non-null   object
 16  Sub-Category    9994 non-null   object
 17  Product Name    9994 non-null   object
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
dtypes: float64(3), int64(4), object(15)
memory usage: 1.7+ MB

In [24]:
df.drop('csvbase_row_id', axis=1, inplace=True)

In [26]:
df.drop('﻿Row ID', axis =1,inplace =True)

In [27]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [28]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [29]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [30]:
df.shape

(9994, 20)

In [35]:
#oulier
Q1=np.percentile(df['Profit'],25,method='midpoint')
Q2=np.percentile(df['Profit'],50,method='midpoint')
Q3=np.percentile(df['Profit'],75,method='midpoint')
print(Q1)
print(Q2)
print(Q3)

1.7295
8.6665
29.364

In [36]:
df['Profit'].median()

8.6665

In [37]:
IQR=Q3-Q1
print(IQR)

27.6345

In [38]:
upperlimit=Q3+1.5*IQR
lowerlimit=Q1-1.5*IQR
print(upperlimit)
print(lowerlimit)

70.81575
-39.722249999999995

In [40]:
outlier=[]
for i in df['Profit']:
    if((i > upperlimit),(i <lowerlimit)):
        outlier.append(i)
outlier

[41.9136,
 219.582,
 6.8714,
 -383.031,
 2.5164,
 14.1694,
 1.9656,
 90.7152,
 5.7825,
 34.47,
 85.3092,
 68.3568,
 5.4432,
 132.5922,
 -123.858,
 -3.816,
 13.3176,
 9.99,
 2.4824,
 16.011,
 7.384,
 5.0596,
 15.6884,
 -1.0196,
 240.2649,
 4.2224,
 11.7741,
 -1665.0522,
 -7.0532,
 15.525,
 1.1016,
 9.7092,
 -5.715,
 3.546,
 9.9468,
 123.4737,
 -147.963,
 35.415,
 -46.9764,
 -15.147,
 41.7564,
 16.5564,
 3.894,
 9.5616,
 19.7714,
 8.2062,
 8.4784,
 4.95,
 6.104,
 17.9634,
 35.3346,
 2.9568,
 17.0981,
 6.2566,
 298.6855,
 52.14,
 15.552,
 7.098,
 6.9888,
 3.3,
 16.362,
 0.84,
 6.1512,
 9.3612,
 68.9631,
 22.3328,
 -15.2225,
 111.3024,
 62.988,
 35.6636,
 1.731,
 8.763,
 -114.3912,
 1.213,
 -18.196,
 -1.9344,
 -5.8248,
 2.724,
 -14.475,
 56.2032,
 8.0352,
 4.172,
 6.2031,
 62.8075,
 -48.9549,
 33.2156,
 6.7966,
 2.9568,
 13.8572,
 6.633,
 8.2782,
 3.1104,
 6.2208,
 16.5354,
 16.1504,
 -3.788,
 40.5426,
 17.9592,
 22.5852,
 22.6184,
 -10.7973,
 -3.0396,
 11.7208,
 -26.8758,
 -3.8385,
 -25.8174,
 17.6016,
 2.0994,
 1.0738,
 67.992,
 10.9096,
 22.788,
 13.3476,
 14.5348,
 1.652,
 7.4925,
 44.0316,
 165.3813,
 -115.7156,
 18.3456,
 13.878,
 63.4368,
 51.759,
 19.7316,
 -8.5794,
 -407.682,
 -1.8308,
 30.499,
 -9.1602,
 26.2416,
 -11.994,
 29.364,
 6.9732,
 9.6192,
 16.6568,
 3.456,
 1.9698,
 26.6616,
 18.4464,
 20.6976,
 10.35,
 2.3814,
 5.1042,
 68.976,
 218.2518,
 20.1579,
 12.9096,
 103.8015,
 5.9988,
 585.552,
 80.6285,
 17.766,
 15.2388,
 26.271,
 48.5392,
 21.0288,
 1.7901,
 51.4764,
 6.8714,
 236.2325,
 2.691,
 1.3596,
 13.348,
 9.688,
 2.7324,
 -1359.992,
 -58.6347,
 -24.858,
 6.8136,
 -453.849,
 8.9985,
 9.8418,
 53.2608,
 21.259,
 -131.12,
 6.552,
 -243.16,
 -11.3372,
 -3.7715,
 1.4104,
 1.8612,
 76.6395,
 131.0296,
 41.986,
 7.25,
 3.4368,
 22.984,
 3.7224,
 6.255,
 112.392,
 20.0928,
 24.8832,
 46.9764,
 6.567,
 6.7116,
 1.2038,
 1.5876,
 12.0276,
 -2.2586,
 5.8203,
 6.795,
 -161.875,
 0.2925,
 -178.9668,
 9.6712,
 44.4768,
 5.8744,
 35.6346,
 7.4824,
 16.2099,
 3.6796,
 6.5,
 8.88,
 -244.323,
 -14.6958,
 -950.4,
 4.4792,
 26.0568,
 22.6782,
 1.8148,
 8.2302,
 -13.8432,
 19.0848,
 -383.9904,
 2.7168,
 0.968,
 136.939,
 0.2198,
 -28.2744,
 43.8408,
 -12.432,
 -102.048,
 -248.2458,
 -3.552,
 0.0,
 -7.7247,
 4.752,
 9.396,
 -356.728,
 -4.6752,
 11.1944,
 -120.513,
 -2.8308,
 1.2038,
 580.5394,
 41.68,
 23.94,
 496.0725,
 12.4416,
 28.1372,
 3.5767,
 636.0003,
 22.5624,
 162.864,
 -8.4924,
 -19.5624,
 4.044,
 56.6916,
 6.9258,
 6.6465,
 6.132,
 -4.466,
 -509.997,
 -251.9958,
 28.7196,
 35.156,
 4.7304,
 0.3024,
 -7.4416,
 21.591,
 210.4936,
 92.3692,
 2.3232,
 4.095,
 4.0572,
 1.5548,
 4.0768,
 5.9072,
 5.9712,
 8.694,
 -3.432,
 376.11,
 51.942,
 47.844,
 47.96,
 10.8864,
 -169.372,
 24.316,
 -204.3145,
 6.6836,
 6.2424,
 54.3966,
 -48.7032,
 78.8592,
 20.1558,
 -24.5646,
 -62.88,
 9.2988,
 15.552,
 10.8248,
 27.3168,
 38.024,
 6.5688,
 -131.445,
 12.864,
 2.8536,
 20.9208,
 83.868,
 2.0049,
 3.5948,
 52.5114,
 1.7136,
 2.0358,
 37.6422,
 22.298,
 5.4432,
 8.6744,
 24.1568,
 1995.99,
 80.0226,
 129.6,
 13.071,
 3.58,
 81.744,
 34.9965,
 0.9995,
 -67.8762,
 3.389,
 -258.5016,
 33.831,
 -27.6936,
 -20.7,
 -13.816,
 -3.4272,
 1.6038,
 335.9944,
 4.49,
 2.7956,
 -17.4588,
 2.3312,
 1.116,
 -407.976,
 10.0724,
 8.3916,
 -2.22,
 4.7976,
 3.0996,
 11.5432,
 4.1472,
 2.3086,
 11.5432,
 1.0668,
 23.0864,
 1415.4296,
 -4.8588,
 3.7996,
 6.9864,
 15.824,
 11.325,
 168.4384,
 9.936,
 9.936,
 86.8704,
 1.4456,
 20.7328,
 8.4784,
 10.44,
 0.1472,
 29.3412,
 271.4192,
 9.396,
 4.6746,
 -5.712,
 179.1888,
 0.924,
 -29.94,
 30.98,
 -297.6848,
 -20.3322,
 2.6811,
 -18.8728,
 25.48,
 17.3376,
 8.799,
 -157.0095,
 -1.0497,
 -337.638,
 0.777,
 0.4264,
 7.884,
 13.5932,
 27.7182,
 701.9883,
 -20.5623,
 25.5798,
 9.4924,
 6.2208,
 21.036,
 3.5952,
 -317.1528,
 -32.784,
 0.7198,
 3.4684,
 9.768,
 9.6957,
 37.7895,
 434.9913,
 13.3035,
 -112.9527,
 4.6464,
 13.608,
 27.4302,
 31.4548,
 -18.4548,
 65.7342,
 26.8744,
 25.8984,
 38.38,
 2.8322,
 2.7028,
 7.015,
 56.5662,
 14.7056,
 8.502,
 225.264,
 11.076,
 138.2016,
 30.0957,
 0.5004,
 -145.3508,
 76.6395,
 54.7425,
 -0.7748,
 207.147,
 -3.6892,
 -18.585,
 43.1991,
 113.6394,
 11.5536,
 2.3094,
 3.666,
 23.3928,
 20.5755,
 42.0256,
 29.1528,
 10.584,
 1.3677,
 15.4752,
 9.7164,
 71.2476,
 7.9248,
 2.8536,
 9.1312,
 -75.8304,
 66.5408,
 24.9132,
 -24.294,
 -96.1146,
 3.348,
 36.372,
 377.9622,
 18.6006,
 7.068,
 -814.4832,
 -20.889,
 -34.758,
 5.8704,
 -312.0614,
 -36.2352,
 -7.9002,
 26.6304,
 3.4092,
 10.4784,
 87.996,
 24.9804,
 28.819,
 45.528,
 7.182,
 19.296,
 6.615,
 84.51,
 1.9089,
 1.6688,
 57.5928,
 14.8,
 -30.245,
 17.4975,
 341.994,
 0.5994,
 10.3974,
 6.1572,
 8.983,
 5.0922,
 13.1572,
 -94.941,
 51.6558,
 40.3704,
 81.8432,
 18.1176,
 22.869,
 -15.08,
 -11.9616,
 50.098,
 -1.9008,
 11.8871,
 5.373,
 0.7398,
 2.1684,
 11.685,
 3177.475,
 40.416,
 12.1728,
 0.7152,
 1.7901,
 1.7052,
 1379.977,
 13.8915,
 5.382,
 56.301,
 5.2877,
 -25.9136,
 -21.168,
 21.098,
 -12.4146,
 27.1666,
 10.434,
 42.747,
 5.1408,
 -7.2672,
 -149.9058,
 19.692,
 11.92,
 2.397,
 274.386,
 11.375,
 1.4672,
 -68.1856,
 3.36,
 41.2938,
 70.98,
 206.316,
 38.0864,
 -145.5246,
 7.264,
 6.2995,
 -84.2928,
 13.932,
 6.4128,
 15.642,
 -17.046,
 -1.744,
 0.0,
 6.0382,
 2.5707,
 310.9872,
 3.4048,
 9.936,
 -217.048,
 15.552,
 16.614,
 27.3182,
 1.3,
 3.7743,
 0.0,
 1.2006,
 46.797,
 45.0016,
 27.3672,
 9.3312,
 0.0,
 34.776,
 6.4216,
 11.2266,
 4.0095,
 2.3814,
 78.7528,
 9.7608,
 2.19,
 8.714,
 -5.7148,
 1.5456,
 52.9173,
 9.2386,
 3.5046,
 -4.7481,
 30.4776,
 4.9686,
 144.5157,
 -20.1362,
 7.2576,
 -12.8961,
 3.6288,
 1.168,
 9.75,
 22.0748,
 434.9913,
 55.745,
 91.7728,
 1.0178,
 -28.7964,
 -115.3544,
 0.73,
 17.847,
 5.1408,
 -5.5338,
 -31.6712,
 47.8152,
 -2.6256,
 2.3814,
 -10.1178,
 41.5773,
 5.6956,
 2.64,
 -157.9383,
 15.992,
 -2.7968,
 15.7872,
 3.0814,
 33.57,
 10.9939,
 27.2862,
 -14.773,
 87.5684,
 178.901,
 130.87,
 46.9278,
 12.0904,
 28.1764,
 5.1435,
 6.0858,
 -51.7191,
 29.95,
 30.0768,
 2.4585,
 85.5297,
 43.2234,
 -13.8468,
 12.2328,
 272.792,
 5.0128,
 6.0288,
 85.904,
 12.6,
 54.3332,
 3.1752,
 56.511,
 9.8625,
 3.0144,
 6.068,
 22.6782,
 31.6,
 178.318,
 45.9754,
 10.312,
 8.5164,
 -2.6544,
 45.3222,
 -50.098,
 -3.462,
 124.929,
 -135.765,
 -118.1295,
 -4.2222,
 18.398,
 5.2626,
 2.079,
 28.7064,
 28.6182,
 8.7285,
 -14.3856,
 -71.8905,
 11.36,
 1.7115,
 16.5888,
 17.505,
 40.7499,
 -7.392,
 4.5201,
 -41.262,
 -320.2395,
 4.6644,
 2.5984,
 18.522,
 -3839.9904,
 14.651,
 163.1898,
 6.8714,
 9.3312,
 4.7996,
 14.5614,
 74.0532,
 10.3152,
 24.936,
 16.032,
 17.3488,
 17.76,
 62.8075,
 31.7512,
 0.8088,
 -13.6312,
 -3.4272,
 4.1448,
 35.6796,
 -13.8717,
 3.6288,
 18.7695,
 2.2824,
 52.7824,
 -110.49,
 15.768,
 26.6304,
 8.8624,
 109.7226,
 89.3142,
 113.9886,
 6.972,
 3.0814,
 24.4758,
 19.4376,
 21.996,
 73.41,
 231.4116,
 80.0199,
 21.112,
 5.1282,
 6.3684,
 5.5992,
 84.0512,
 -153.3456,
 10.089,
 102.4998,
 3.024,
 9.7176,
 86.3856,
 33.6474,
 9.4284,
 18.6956,
 6.552,
 8.4966,
 4.2717,
 -64.7748,
 -5.487,
 -10.948,
 1.1466,
 1.6762,
 6.2064,
 -28.356,
 7.1864,
 0.8994,
 26.703,
 56.7864,
 22.792,
 1.4112,
 374.9925,
 28.7712,
 -167.3184,
 6.8768,
 47.92,
 4.2666,
 10.224,
 27.9936,
 5.6994,
 -26.9955,
 5.3392,
 25.47,
 258.696,
 2.7072,
 34.3548,
 23.316,
 179.7488,
 9.14,
 51.75,
 16.175,
 3.4695,
 10.881,
 14.5236,
 3.6855,
 40.8006,
 28.1718,
 11.7208,
 1.926,
 -22.449,
 -2.7,
 -15.6156,
 0.5998,
 87.7443,
 5.8914,
 34.8928,
 69.1008,
 4.1634,
 21.0896,
 79.9056,
 85.2475,
 4.5816,
 10.6428,
 9.8784,
 63.7392,
 6.2208,
 10.3488,
 17.745,
 7.3359,
 18.8972,
 99.4896,
 6.2208,
 6.2152,
 4.3176,
 247.996,
 11.076,
 50.9898,
 3.2256,
 311.652,
 62.0368,
 2.578,
 6.2152,
 601.9699,
 24.8832,
 1.8704,
 14.5152,
 -2.4288,
 0.0,
 -22.7964,
 117.432,
 71.991,
 4.8118,
 4.068,
 40.3128,
 16.8,
 10.7996,
 7.4872,
 90.588,
 50.5848,
 51.8346,
 17.1574,
 2.6412,
 6.5164,
 -111.4995,
 -79.3352,
 3.2616,
 1.5804,
 16.3215,
 3.3408,
 9.3024,
 11.7,
 8.7672,
 3.2944,
 6.8714,
 23.4416,
 77.7438,
 8.5568,
 49.6048,
 1.3416,
 18.6624,
 50.1876,
 14.6718,
 9.7176,
 18.7812,
 26.598,
 5.7672,
 3.5767,
 3.58,
 0.1472,
 10.626,
 40.6878,
 0.5904,
 5.1786,
 1.3583,
 21.2954,
 5.1792,
 -35.928,
 -760.98,
 -46.797,
 17.22,
 5.2256,
 37.2204,
 67.256,
 64.518,
 13.1956,
 66.9546,
 -4.1244,
 23.1093,
 262.39,
 8.3268,
 5.9312,
 10.048,
 5.9364,
 4.5318,
 1.6752,
 18.4534,
 16.9932,
 14.995,
 18.6006,
 2.043,
 5.4128,
 135.98,
 42.0714,
 24.5028,
 5.0856,
 51.8,
 22.5408,
 -6.5296,
 3.393,
 -32.088,
 20.2485,
 9.6192,
 2.5984,
 6.2208,
 12.1176,
 2.7279,
 19.791,
 323.946,
 829.3754,
 81.0474,
 9.102,
 19.2454,
 56.0547,
 -18.5562,
 -56.996,
 -14.5656,
 50.4063,
 -0.812,
 6.8768,
 34.9074,
 10.5552,
 113.848,
 294.5488,
 5.4432,
 53.55,
 12.936,
 9.5172,
 2.5536,
 21.3408,
 5.0286,
 4.1148,
 15.2064,
 -21.7932,
 5.4432,
 33.5772,
 54.3966,
 6.2208,
 34.9648,
 8.0464,
 2.2098,
 41.7852,
 15.552,
 140.5482,
 62.91,
 -204.4458,
 -12.9122,
 75.5424,
 -619.596,
 5.4432,
 7.92,
 7.6416,
 2.7168,
 -11.596,
 43.45,
 2.5893,
 -3.168,
 5.6376,
 53.196,
 28.1372,
 3.0576,
 10.94,
 1.6704,
 4.8118,
 9.7119,
 6.2208,
 91.968,
 4.2336,
 0.0,
 28.5984,
 -31.05,
 -13.6312,
 10.1493,
 3.2186,
 25.5798,
 -0.792,
 679.996,
 -2.6256,
 16.6698,
 93.2232,
 0.8056,
 55.9984,
 75.49,
 2.5896,
 9.4392,
 44.868,
 -1.8904,
 72.807,
 5.2113,
 131.2785,
 5.484,
 4.9104,
 69.705,
 1276.4871,
 173.0316,
 4.9082,
 9.8901,
 9.158,
 12.9129,
 ...]

In [41]:
df.dtypes

Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [42]:
colm=['Postal Code','Sales','Quantity','Discount','Profit']
df_cleaned=df.copy()

for col in colm:
    Q1 =df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    df_cleaned = df_cleaned[
        (df_cleaned[col] >= Q1-1.5*IQR)&
        (df_cleaned[col] <= Q3+ 1.5*IQR)
    ]
print("Before:" , df.shape)
print("After:", df_cleaned.shape)

Before: (9994, 20)
After: (7143, 20)

In [44]:
df.dtypes

Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le=LabelEncoder()

In [49]:
coln=['Order ID','Order Date','Ship Date','Ship Mode','Customer ID','Customer Name',
      'Segment','Country','City','State','Region','Product ID','Category','Sub-Category',
     'Product Name']

for i in coln:
    df[i]=le.fit_transform(df[i])

In [50]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2500,864,929,2,143,166,0,0,194,15,42420,2,12,0,4,386,261.9600,2,0.00,41.9136
1,2500,864,929,2,143,166,0,0,194,15,42420,2,55,0,5,839,731.9400,3,0.00,219.5820
2,2296,732,787,2,237,201,1,0,266,3,90036,3,946,1,10,1433,14.6200,2,0.00,6.8714
3,4372,519,568,3,705,687,0,0,153,8,33311,2,319,0,16,366,957.5775,5,0.45,-383.0310
4,4372,519,568,3,705,687,0,0,153,8,33311,2,1316,1,14,573,22.3680,2,0.20,2.5164

In [53]:
x =df.drop(['Profit'],axis=1,inplace=False)

In [67]:
y=df['Profit']
y

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [68]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2500,864,929,2,143,166,0,0,194,15,42420,2,12,0,4,386,261.9600,2,0.00,41.9136
1,2500,864,929,2,143,166,0,0,194,15,42420,2,55,0,5,839,731.9400,3,0.00,219.5820
2,2296,732,787,2,237,201,1,0,266,3,90036,3,946,1,10,1433,14.6200,2,0.00,6.8714
3,4372,519,568,3,705,687,0,0,153,8,33311,2,319,0,16,366,957.5775,5,0.45,-383.0310
4,4372,519,568,3,705,687,0,0,153,8,33311,2,1316,1,14,573,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,138,15,12,2,737,758,0,0,295,8,33180,2,200,0,9,1586,25.2480,3,0.20,4.1028
9990,3216,956,1033,3,190,202,0,0,104,3,92627,3,164,0,9,1535,91.9600,2,0.00,15.6332
9991,3216,956,1033,3,190,202,0,0,104,3,92627,3,1816,2,13,47,258.5760,2,0.20,19.3932
9992,3216,956,1033,3,190,202,0,0,104,3,92627,3,1247,1,12,929,29.6000,4,0.00,13.3200
9993,3194,1016,1096,2,130,146,0,0,517,3,92683,3,433,1,1,54,243.1600,2,0.00,72.9480

In [56]:
from sklearn.preprocessing import MinMaxScaler

In [57]:
minmax=MinMaxScaler(feature_range=(0,1))

In [58]:
x1=minmax.fit_transform(x)

In [59]:
x1

array([[4.99201278e-01, 6.99029126e-01, 6.96924231e-01, ...,
        1.15520622e-02, 7.69230769e-02, 0.00000000e+00],
       [4.99201278e-01, 6.99029126e-01, 6.96924231e-01, ...,
        3.23126971e-02, 1.53846154e-01, 0.00000000e+00],
       [4.58466454e-01, 5.92233010e-01, 5.90397599e-01, ...,
        6.26202732e-04, 7.69230769e-02, 0.00000000e+00],
       ...,
       [6.42172524e-01, 7.73462783e-01, 7.74943736e-01, ...,
        1.14025793e-02, 7.69230769e-02, 2.50000000e-01],
       [6.42172524e-01, 7.73462783e-01, 7.74943736e-01, ...,
        1.28792091e-03, 2.30769231e-01, 0.00000000e+00],
       [6.37779553e-01, 8.22006472e-01, 8.22205551e-01, ...,
        1.07216015e-02, 7.69230769e-02, 0.00000000e+00]])

In [60]:
type(x1)

numpy.ndarray

In [61]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [64]:
x2=pd.DataFrame(x1,columns=['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount'])

In [65]:
x2.describe()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.0,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,0.498251,0.569185,0.567962,0.745014,0.505632,0.505826,0.329498,0.0,0.528221,0.465483,0.551087,0.523547,0.482790,0.486292,0.474403,0.498824,0.010134,0.214583,0.195253
std,0.291651,0.289056,0.290436,0.366960,0.288618,0.288263,0.381311,0.0,0.262562,0.323013,0.326311,0.387443,0.283024,0.314772,0.315714,0.287461,0.027531,0.171162,0.258065
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.239467,0.331715,0.327832,0.666667,0.259154,0.253788,0.000000,0.0,0.309434,0.083333,0.225756,0.333333,0.243418,0.500000,0.187500,0.256490,0.000744,0.076923,0.000000
50%,0.498802,0.602751,0.600150,1.000000,0.511995,0.512626,0.000000,0.0,0.556604,0.562500,0.563708,0.333333,0.463729,0.500000,0.562500,0.490535,0.002387,0.153846,0.250000
75%,0.750948,0.829288,0.828957,1.000000,0.760101,0.753788,0.500000,0.0,0.743396,0.750000,0.905425,1.000000,0.723804,0.500000,0.750000,0.751758,0.009254,0.307692,0.250000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [69]:
x3=pd.concat([x2,y],axis=1)

In [70]:
x3

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0.499201,0.699029,0.696924,0.666667,0.180556,0.209596,0.0,0.0,0.366038,0.312500,0.421123,0.666667,0.006448,0.0,0.2500,0.208761,0.011552,0.076923,0.0000,41.9136
1,0.499201,0.699029,0.696924,0.666667,0.180556,0.209596,0.0,0.0,0.366038,0.312500,0.421123,0.666667,0.029554,0.0,0.3125,0.453759,0.032313,0.153846,0.0000,219.5820
2,0.458466,0.592233,0.590398,0.666667,0.299242,0.253788,0.5,0.0,0.501887,0.062500,0.905710,1.000000,0.508329,0.5,0.6250,0.775014,0.000626,0.076923,0.0000,6.8714
3,0.873003,0.419903,0.426107,1.000000,0.890152,0.867424,0.0,0.0,0.288679,0.166667,0.328421,0.666667,0.171413,0.0,1.0000,0.197945,0.042280,0.307692,0.5625,-383.0310
4,0.873003,0.419903,0.426107,1.000000,0.890152,0.867424,0.0,0.0,0.288679,0.166667,0.328421,0.666667,0.707147,0.5,0.8750,0.309897,0.000968,0.076923,0.2500,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,0.027556,0.012136,0.009002,0.666667,0.930556,0.957071,0.0,0.0,0.556604,0.166667,0.327088,0.666667,0.107469,0.0,0.5625,0.857761,0.001096,0.153846,0.2500,4.1028
9990,0.642173,0.773463,0.774944,1.000000,0.239899,0.255051,0.0,0.0,0.196226,0.062500,0.932079,1.000000,0.088125,0.0,0.5625,0.830178,0.004043,0.076923,0.0000,15.6332
9991,0.642173,0.773463,0.774944,1.000000,0.239899,0.255051,0.0,0.0,0.196226,0.062500,0.932079,1.000000,0.975819,1.0,0.8125,0.025419,0.011403,0.076923,0.2500,19.3932
9992,0.642173,0.773463,0.774944,1.000000,0.239899,0.255051,0.0,0.0,0.196226,0.062500,0.932079,1.000000,0.670070,0.5,0.7500,0.502434,0.001288,0.230769,0.0000,13.3200
9993,0.637780,0.822006,0.822206,0.666667,0.164141,0.184343,0.0,0.0,0.975472,0.062500,0.932649,1.000000,0.232671,0.5,0.0625,0.029205,0.010722,0.076923,0.0000,72.9480

In [71]:
from sklearn.preprocessing import StandardScaler

In [72]:
std=StandardScaler()

In [73]:
x1=std.fit_transform(x)

In [74]:
x1=pd.DataFrame(x1,columns=['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount'])

In [75]:
x1

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount
0,0.003260,0.449222,0.444053,-0.213513,-1.126376,-1.027688,-0.864161,0.0,-0.617727,-0.473638,-0.398302,0.369413,-1.683126,-1.544978,-0.710815,-1.009098,0.051510,-0.804303,-0.756643
1,0.003260,0.449222,0.444053,-0.213513,-1.126376,-1.027688,-0.864161,0.0,-0.617727,-0.473638,-0.398302,0.369413,-1.601483,-1.544978,-0.512842,-0.156776,0.805633,-0.354865,-0.756643
2,-0.136417,0.079738,0.077253,-0.213513,-0.715131,-0.874376,0.447170,0.0,-0.100303,-1.247640,1.086817,1.229798,0.090240,0.043552,0.477027,0.960838,-0.345368,-0.804303,-0.756643
3,1.284998,-0.516474,-0.488446,0.694896,1.332345,1.254465,-0.864161,0.0,-0.912371,-0.925139,-0.682407,0.369413,-1.100232,-1.544978,1.664869,-1.046728,1.167688,0.544012,1.423149
4,1.284998,-0.516474,-0.488446,0.694896,1.332345,1.254465,-0.864161,0.0,-0.912371,-0.925139,-0.682407,0.369413,0.792751,0.043552,1.268921,-0.657256,-0.332935,-0.804303,0.212153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,-1.613975,-1.927229,-1.924650,-0.213513,1.472343,1.565469,-0.864161,0.0,0.108104,-0.925139,-0.686492,0.369413,-1.326175,-1.544978,0.279053,1.248708,-0.328314,-0.354865,0.212153
9990,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,-1.394527,-1.544978,0.279053,1.152752,-0.221269,-0.804303,-0.756643
9991,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,1.742090,1.632082,1.070948,-1.646928,0.046080,-0.804303,0.212153
9992,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,0.661742,0.043552,0.872974,0.012559,-0.321331,0.094574,-0.756643
9993,0.478434,0.874688,0.875431,-0.213513,-1.183250,-1.115295,-0.864161,0.0,1.703494,-1.247640,1.169375,1.229798,-0.883782,0.043552,-1.304737,-1.633758,0.021344,-0.804303,-0.756643

In [76]:
x1.describe()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount
count,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9994.0,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03,9.994000e+03
mean,-9.669183e-17,-8.958213e-17,-1.137551e-17,1.521474e-16,-1.421939e-17,-1.777423e-17,7.109693e-18,0.0,-1.884069e-16,-9.669183e-17,-8.673826e-17,-1.564132e-17,3.199362e-17,5.829948e-17,2.132908e-17,1.066454e-17,-4.550204e-17,4.870140e-17,7.251887e-17
std,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,0.0,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00
min,-1.708462e+00,-1.969215e+00,-1.955647e+00,-2.030332e+00,-1.751993e+00,-1.754823e+00,-8.641609e-01,0.0,-2.011896e+00,-1.441141e+00,-1.688922e+00,-1.351357e+00,-1.705910e+00,-1.544978e+00,-1.502710e+00,-1.735359e+00,-3.681144e-01,-1.253742e+00,-7.566435e-01
25%,-8.873491e-01,-8.215773e-01,-8.268324e-01,-2.135135e-01,-8.540353e-01,-8.743765e-01,-8.641609e-01,0.0,-8.333201e-01,-1.183140e+00,-9.970461e-01,-4.909720e-01,-8.458089e-01,4.355184e-02,-9.087892e-01,-8.430550e-01,-3.410996e-01,-8.043034e-01,-7.566435e-01
50%,1.890602e-03,1.161270e-01,1.108329e-01,6.948960e-01,2.204809e-02,2.359173e-02,-8.641609e-01,0.0,1.081037e-01,3.003640e-01,3.867872e-02,-4.909720e-01,-6.735065e-02,4.355184e-02,2.790530e-01,-2.883368e-02,-2.813929e-01,-3.548649e-01,2.121533e-01
75%,8.664815e-01,8.998798e-01,8.986784e-01,6.948960e-01,8.817254e-01,8.602353e-01,4.471698e-01,0.0,8.195613e-01,8.808655e-01,1.085944e+00,1.229798e+00,8.516098e-01,4.355184e-02,8.729740e-01,8.799333e-01,-3.196013e-02,5.440122e-01,2.121533e-01
max,1.720460e+00,1.490494e+00,1.487625e+00,6.948960e-01,1.712966e+00,1.714400e+00,1.758501e+00,0.0,1.796917e+00,1.654868e+00,1.375787e+00,1.229798e+00,1.827531e+00,1.632082e+00,1.664869e+00,1.743544e+00,3.595655e+01,4.588959e+00,3.118544e+00

In [77]:
x2=pd.concat([x1,y],axis=1)

In [78]:
x2

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0.003260,0.449222,0.444053,-0.213513,-1.126376,-1.027688,-0.864161,0.0,-0.617727,-0.473638,-0.398302,0.369413,-1.683126,-1.544978,-0.710815,-1.009098,0.051510,-0.804303,-0.756643,41.9136
1,0.003260,0.449222,0.444053,-0.213513,-1.126376,-1.027688,-0.864161,0.0,-0.617727,-0.473638,-0.398302,0.369413,-1.601483,-1.544978,-0.512842,-0.156776,0.805633,-0.354865,-0.756643,219.5820
2,-0.136417,0.079738,0.077253,-0.213513,-0.715131,-0.874376,0.447170,0.0,-0.100303,-1.247640,1.086817,1.229798,0.090240,0.043552,0.477027,0.960838,-0.345368,-0.804303,-0.756643,6.8714
3,1.284998,-0.516474,-0.488446,0.694896,1.332345,1.254465,-0.864161,0.0,-0.912371,-0.925139,-0.682407,0.369413,-1.100232,-1.544978,1.664869,-1.046728,1.167688,0.544012,1.423149,-383.0310
4,1.284998,-0.516474,-0.488446,0.694896,1.332345,1.254465,-0.864161,0.0,-0.912371,-0.925139,-0.682407,0.369413,0.792751,0.043552,1.268921,-0.657256,-0.332935,-0.804303,0.212153,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,-1.613975,-1.927229,-1.924650,-0.213513,1.472343,1.565469,-0.864161,0.0,0.108104,-0.925139,-0.686492,0.369413,-1.326175,-1.544978,0.279053,1.248708,-0.328314,-0.354865,0.212153,4.1028
9990,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,-1.394527,-1.544978,0.279053,1.152752,-0.221269,-0.804303,-0.756643,15.6332
9991,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,1.742090,1.632082,1.070948,-1.646928,0.046080,-0.804303,0.212153,19.3932
9992,0.493497,0.706741,0.712695,0.694896,-0.920753,-0.869996,-0.864161,0.0,-1.264507,-1.247640,1.167629,1.229798,0.661742,0.043552,0.872974,0.012559,-0.321331,0.094574,-0.756643,13.3200
9993,0.478434,0.874688,0.875431,-0.213513,-1.183250,-1.115295,-0.864161,0.0,1.703494,-1.247640,1.169375,1.229798,-0.883782,0.043552,-1.304737,-1.633758,0.021344,-0.804303,-0.756643,72.9480

In [79]:
df.to_csv('super_sum.csv',index=False)

In [81]:
df=pd.read_csv('super_sum.csv')

In [82]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2500,864,929,2,143,166,0,0,194,15,42420,2,12,0,4,386,261.9600,2,0.00,41.9136
1,2500,864,929,2,143,166,0,0,194,15,42420,2,55,0,5,839,731.9400,3,0.00,219.5820
2,2296,732,787,2,237,201,1,0,266,3,90036,3,946,1,10,1433,14.6200,2,0.00,6.8714
3,4372,519,568,3,705,687,0,0,153,8,33311,2,319,0,16,366,957.5775,5,0.45,-383.0310
4,4372,519,568,3,705,687,0,0,153,8,33311,2,1316,1,14,573,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,138,15,12,2,737,758,0,0,295,8,33180,2,200,0,9,1586,25.2480,3,0.20,4.1028
9990,3216,956,1033,3,190,202,0,0,104,3,92627,3,164,0,9,1535,91.9600,2,0.00,15.6332
9991,3216,956,1033,3,190,202,0,0,104,3,92627,3,1816,2,13,47,258.5760,2,0.20,19.3932
9992,3216,956,1033,3,190,202,0,0,104,3,92627,3,1247,1,12,929,29.6000,4,0.00,13.3200
9993,3194,1016,1096,2,130,146,0,0,517,3,92683,3,433,1,1,54,243.1600,2,0.00,72.9480